# Generated by Django 4.2 on 2024-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('Course_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
