# Generated by Django 4.2 on 2024-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
